<a href="https://colab.research.google.com/github/Adela-Jones/datasci_1_loading/blob/main/507_HW_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**The following code cell below imports pandas and json**

we need pandas because we cannot load our dataset without it
we need json to be able to read json files

In [2]:
import pandas as pd
import json

In [4]:
df1 = '/content/Data/Medicare_Provider_and_Supplier_Taxonomy_Crosswalk_Aug_24_2026.csv'
read_df1 = pd.read_csv(df1)
read_df1.head(11)

,MEDICARE SPECIALTY CODE,MEDICARE PROVIDER/SUPPLIER TYPE DESCRIPTION,PROVIDER TAXONOMY CODE,"PROVIDER TAXONOMY DESCRIPTION: TYPE, CLASSIFICATION, SPECIALIZATION"
0,01,Physician/General Practice,208D00000X,Allopathic & Osteopathic Physicians/General Pr...
1,02,Physician/General Surgery,208600000X,Allopathic & Osteopathic Physicians/Surgery
2,02,Physician/General Surgery,2086H0002X,Allopathic & Osteopathic Physicians/Surgery/Ho...
3,02,Physician/General Surgery,2086S0120X,Allopathic & Osteopathic Physicians/Surgery/Pe...
4,02,Physician/General Surgery,2086S0122X,Allopathic & Osteopathic Physicians/Surgery/Pl...
5,02,Physician/General Surgery,2086S0105X,Allopathic & Osteopathic Physicians/Surgery/Su...
6,02,Physician/General Surgery,2086S0102X,Allopathic & Osteopathic Physicians/Surgery/Su...
7,02,Physician/General Surgery,2086X0206X,Allopathic & Osteopathic Physicians/Surgery/Su...
8,02,Physician/General Surgery,2086S0127X,Allopathic & Osteopathic Physicians/Surgery/Tr...
9,02,Physician/General Surgery,2086S0129X,Allopathic & Osteopathic Physicians/Surgery/Va...
10,02,Physician/General Surgery,208G00000X,Allopathic & Osteopathic Physicians/Thoracic S...

**df1 represents the following:**
Information about Medicare provider/supplier Taxonomy extracted August 2026

**Columns**

**1. Medicare Specialty Code**
* Two digit numeric identifiers used by CMS to desigante a healthcare providers or supplier's primary area of practice

**2. Medicare Provider/Supplier Type Description**
* Classifies the category of healthcare professional, facility, or facility enrolled in Medicare

**3. Provider Taxonomy Code**
* A 10 character alphanumeric code that classifies a healthcare providers specific profession, clinical classification and area of specialization

**4. Provider Taxonomy Description: Type, Classification, Specialization**
* Represents the complete hierarchical structure used to categorize healthcare professionals and facilities in the United States

In [6]:
df2= '/content/Data/Medicare_Telehealth_Trends_Q1_2026.csv'
read_df2=pd.read_csv(df2)
read_df2.head(11)

,Year,quarter,Bene_Geo_Desc,Bene_Mdcd_Mdcr_Enrl_Stus,Bene_Race_Desc,Bene_Sex_Desc,Bene_Mdcr_Entlmt_Stus,Bene_Age_Desc,Bene_RUCA_Desc,Total_Bene_TH_Elig,Total_PartB_Enrl,Total_Bene_Telehealth,Pct_Telehealth
0,2020,Overall,National,All,All,All,All,All,All,30946785.0,3.224489e+07,14826919.0,0.4791
1,2020,Overall,National,All,All,All,All,All,Rural,7182616.0,7.493527e+06,2859483.0,0.3981
2,2020,Overall,National,All,All,All,All,All,Urban,23699049.0,2.463142e+07,11945312.0,0.5040
3,2020,Overall,National,All,All,All,All,All,Unknown,NaN,NaN,NaN,NaN
4,2020,Overall,National,All,All,All,All,0-64,All,4088345.0,4.291403e+06,2322324.0,0.5680
5,2020,Overall,National,All,All,All,All,65-74,All,14440791.0,1.532671e+07,6495728.0,0.4498
6,2020,Overall,National,All,All,All,All,75-84,All,8507543.0,8.770470e+06,4133907.0,0.4859
7,2020,Overall,National,All,All,All,All,85 and over,All,3910106.0,3.856306e+06,1874960.0,0.4795
8,2020,Overall,National,All,All,All,Aged,All,All,26643001.0,2.776232e+07,12371786.0,0.4644
9,2020,Overall,National,All,All,All,Disabled,All,All,3869764.0,4.092286e+06,2192809.0,0.5667
10,2020,Overall,National,All,All,All,ESRD,All,All,434020.0,3.902881e+05,262324.0,0.6044

**Df2 represent the following:**
Information regarding Telehealth Trends extracted in Q1 2026

**Columns:**

**1. Year**
* Identifies the year from which the data was extracted from

**2. Quarter**
* Represents the data quarter from where the data was pulled

**3. Beneficiary Geographic Description**
* Provides the text name of a geographic area

**4. Beneficiary Medicaid Medicare Enrollment Status**
* Indicates whether the beneficiary is dually eligible for both programs

**5.Beneficiary Race Description**
* Describes a beneficiary's racial or ethnic identity

**6.Beneficiary Sex Description**
* Describes the biological sex of the beneficiary

**7.Beneficiary Medicare Entitlement Status**

* Defines whether the beneficiary is qualified, enrolled and active to recieve benefits under the Medicare program

**8.Beneficiary Age Description**

* Provides a breakdown of the beneficiary's age

**9.Beneficiary RUCA Description**

* Lists whether the beneficiary lives in an urban or rural commuting area

**10. Total Beneficiary TeleHealth Eligibility**

* Represents the complete count of Medicare beneficiaries who are eligible to receive Telehealth services

**11.Total Part B Enrollment**

* Represents the total amount of beneficiaries who are enrolled in Part B

**12.Total Beneficiary Telehealth**

* Represents the number of unique Medicare beneficiaries with Telehealth

**13. Percent TeleHealth**

* Represents the percentage of unique Medicare beneficiaries who used a telehealth service

In [10]:
df3='/content/Data/Home_Infusion_Therapy_Providers_Sep_21_2026.csv'
read_df3=pd.read_csv(df3)
read_df3.head(11)

,Enrollment ID,Legal Business Name,Street Address Line 1,Street Address Line 2,City,State,ZIP Code,Practice Location Phone Number,Specialty Name,Geographic Location Type Description,Geographic Location City Name,Geographic Location State Code,Geographic Location ZIP Code,State County Name
0,O20201116001628,CRESCENT HEALTHCARE INC,5431 SW 35TH DR,STE 200,GAINESVILLE,FL,32608-5277,(844) 373-8389,HOME INFUSION THERAPY SUPPLIER,RENDERING AREA,--,FL,--,--
1,O20250730000500,"KABAFUSION CO, LLC",12450 E ARAPAHOE RD,--,CENTENNIAL,CO,80112-3971,(877) 369-7213,HOME INFUSION THERAPY SUPPLIER,RENDERING AREA,--,CO,--,--
2,O20210121000184,I V SOLUTIONS LLC,165 HANSEN CT,STE 106,WOOD DALE,IL,60191-1110,8479454444-1110,HOME INFUSION THERAPY SUPPLIER,RENDERING AREA,--,IL,--,LAKE
3,O20231019000440,PERPETUAL MOBILE MED,5015 EAGLE ROCK BLVD,STE 200,LOS ANGELES,CA,90041-2087,(323) 455-4868,HOME INFUSION THERAPY SUPPLIER,RENDERING AREA,--,CA,--,--
4,O20220203001062,MKARE MANAGEMENT INC,147 AUBURN RDG,--,SPRING BRANCH,TX,78070-6001,(210) 663-1886,HOME INFUSION THERAPY SUPPLIER,RENDERING AREA,--,TX,--,GUADALUPE
5,O20250428002383,INFUPHARMA LLC,1239 NE 8TH AVE,--,FORT LAUDERDALE,FL,33304-2001,(954) 923-3839,HOME INFUSION THERAPY SUPPLIER,RENDERING AREA,--,FL,--,--
6,O20260127003422,KABAFUSION TN LLC,2970 SIDCO DR,--,NASHVILLE,TN,37204-3715,(877) 397-8341,HOME INFUSION THERAPY SUPPLIER,RENDERING AREA,--,GA,--,--
7,O20260914004301,AMERICARE HOME HEALTH INC,16501 SHERMAN WAY,STE 225,VAN NUYS,CA,91406-3787,(818) 881-0005,HOME INFUSION THERAPY SUPPLIER,RENDERING AREA,--,CA,--,SAN DIEGO
8,O20260914004301,AMERICARE HOME HEALTH INC,16501 SHERMAN WAY,STE 225,VAN NUYS,CA,91406-3787,(818) 881-0005,HOME INFUSION THERAPY SUPPLIER,SUPPLIER GR. AREA,--,CA,--,ORANGE
9,O20260914004301,AMERICARE HOME HEALTH INC,16501 SHERMAN WAY,STE 225,VAN NUYS,CA,91406-3787,(818) 881-0005,HOME INFUSION THERAPY SUPPLIER,SUPPLIER GR. AREA,--,CA,--,TULARE
10,O20260325003657,AGIOS CORP,1314 S BAY ST,--,EUSTIS,FL,32726-5551,(325) 357-6699,HOME INFUSION THERAPY SUPPLIER,RENDERING AREA,--,FL,--,--

**DF3 represents the following: **
Information on the providers in Medicare who specialize in Home Infusion Therapy

**Columns:**

**1. Enrollment ID**
* Represents the enrollment ID of the provider

**2. Legal Business Name**

* Represents the legal business name of the organization

**3. Street Address Line 1**

* Represents the 1st line of the street address

**4. Street Address Line 2**

* Represents the 2nd line of the street address

**5. City**

* Represents the City the practice is located

**6. State**

* Represents the State the practice is located

**7. ZIP Code**

* Represents the Zip code of the organization

**8. Practice Location Phone Number**

* Represents the phone number of the practice location

**9. Specialty Name**

* Represents the providers specialty

**10. Geographic Location Type Description**

* Represents the geographic location the practice is in

**11. Geographic Location City Name**

* Represents the City of the practices geographic location

**12. Geographic Location State Code**

* Represents the State code of the geographic location the practice is in

**13. Geographic Location ZIP Code**

* Represents the ZIP Code of the geographic location the practice is in

**14. State County Name**
* Represents the State County name in which the practice is located